package ops.gateway.entities;
// Generated Feb 1, 2020 10:38:55 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestToService generated by hbm2java
 */
@Entity
@Table(name = "request_to_service", catalog = "ops_pay_service")
public class RequestToService implements java.io.Serializable {

	private long objectId;
	private String requestServiceId;
	private Date requestTime;
	private String requestBody;
	private String responseServiceId;
	private Date responseTime;
	private String responseCode;
	private String responseMsg;
	private String responseBody;

	public RequestToService() {
	}

	public RequestToService(long objectId) {
		this.objectId = objectId;
	}

	public RequestToService(long objectId, String requestServiceId, Date requestTime, String requestBody,
			String responseServiceId, Date responseTime, String responseCode, String responseMsg, String responseBody) {
		this.objectId = objectId;
		this.requestServiceId = requestServiceId;
		this.requestTime = requestTime;
		this.requestBody = requestBody;
		this.responseServiceId = responseServiceId;
		this.responseTime = responseTime;
		this.responseCode = responseCode;
		this.responseMsg = responseMsg;
		this.responseBody = responseBody;
	}

	@Id

	@Column(name = "OBJECT_ID", unique = true, nullable = false)
	public long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(long objectId) {
		this.objectId = objectId;
	}

	@Column(name = "REQUEST_SERVICE_ID", length = 100)
	public String getRequestServiceId() {
		return this.requestServiceId;
	}

	public void setRequestServiceId(String requestServiceId) {
		this.requestServiceId = requestServiceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_TIME", length = 19)
	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "REQUEST_BODY", length = 65535)
	public String getRequestBody() {
		return this.requestBody;
	}

	public void setRequestBody(String requestBody) {
		this.requestBody = requestBody;
	}

	@Column(name = "RESPONSE_SERVICE_ID", length = 100)
	public String getResponseServiceId() {
		return this.responseServiceId;
	}

	public void setResponseServiceId(String responseServiceId) {
		this.responseServiceId = responseServiceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESPONSE_TIME", length = 19)
	public Date getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	@Column(name = "RESPONSE_CODE", length = 30)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "RESPONSE_MSG", length = 65535)
	public String getResponseMsg() {
		return this.responseMsg;
	}

	public void setResponseMsg(String responseMsg) {
		this.responseMsg = responseMsg;
	}

	@Column(name = "RESPONSE_BODY", length = 65535)
	public String getResponseBody() {
		return this.responseBody;
	}

	public void setResponseBody(String responseBody) {
		this.responseBody = responseBody;
	}

}
