package ops.gateway.entities;
// Generated Feb 1, 2020 10:38:55 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestMaster generated by hbm2java
 */
@Entity
@Table(name = "request_master", catalog = "ops_pay_service")
public class RequestMaster implements java.io.Serializable {

	private Long objectId;
	private String originalTransId;
	private String makerRequestId;
	private long makerId;
	private String makerName;
	private Date makedTime;
	private String transactionType;
	private String actionType;
	private String data;
	private Long checkerId;
	private String checkerName;
	private Date checkedTime;
	private String status;
	private String result;
	private String comment;
	private Date responseTime;
	private String responseTransId;

	public RequestMaster() {
	}

	public RequestMaster(String makerRequestId, long makerId, String transactionType, String actionType, String data,
			String status, String result) {
		this.makerRequestId = makerRequestId;
		this.makerId = makerId;
		this.transactionType = transactionType;
		this.actionType = actionType;
		this.data = data;
		this.status = status;
		this.result = result;
	}

	public RequestMaster(String originalTransId, String makerRequestId, long makerId, String makerName, Date makedTime,
			String transactionType, String actionType, String data, Long checkerId, String checkerName,
			Date checkedTime, String status, String result, String comment, Date responseTime, String responseTransId) {
		this.originalTransId = originalTransId;
		this.makerRequestId = makerRequestId;
		this.makerId = makerId;
		this.makerName = makerName;
		this.makedTime = makedTime;
		this.transactionType = transactionType;
		this.actionType = actionType;
		this.data = data;
		this.checkerId = checkerId;
		this.checkerName = checkerName;
		this.checkedTime = checkedTime;
		this.status = status;
		this.result = result;
		this.comment = comment;
		this.responseTime = responseTime;
		this.responseTransId = responseTransId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OBJECT_ID", unique = true, nullable = false)
	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	@Column(name = "ORIGINAL_TRANS_ID", length = 100)
	public String getOriginalTransId() {
		return this.originalTransId;
	}

	public void setOriginalTransId(String originalTransId) {
		this.originalTransId = originalTransId;
	}

	@Column(name = "MAKER_REQUEST_ID", nullable = false, length = 100)
	public String getMakerRequestId() {
		return this.makerRequestId;
	}

	public void setMakerRequestId(String makerRequestId) {
		this.makerRequestId = makerRequestId;
	}

	@Column(name = "MAKER_ID", nullable = false)
	public long getMakerId() {
		return this.makerId;
	}

	public void setMakerId(long makerId) {
		this.makerId = makerId;
	}

	@Column(name = "MAKER_NAME", length = 150)
	public String getMakerName() {
		return this.makerName;
	}

	public void setMakerName(String makerName) {
		this.makerName = makerName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MAKED_TIME", length = 19)
	public Date getMakedTime() {
		return this.makedTime;
	}

	public void setMakedTime(Date makedTime) {
		this.makedTime = makedTime;
	}

	@Column(name = "TRANSACTION_TYPE", nullable = false, length = 50)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "ACTION_TYPE", nullable = false, length = 50)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "DATA", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "CHECKER_ID")
	public Long getCheckerId() {
		return this.checkerId;
	}

	public void setCheckerId(Long checkerId) {
		this.checkerId = checkerId;
	}

	@Column(name = "CHECKER_NAME", length = 150)
	public String getCheckerName() {
		return this.checkerName;
	}

	public void setCheckerName(String checkerName) {
		this.checkerName = checkerName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHECKED_TIME", length = 19)
	public Date getCheckedTime() {
		return this.checkedTime;
	}

	public void setCheckedTime(Date checkedTime) {
		this.checkedTime = checkedTime;
	}

	@Column(name = "STATUS", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "RESULT", nullable = false, length = 10)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESPONSE_TIME", length = 19)
	public Date getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	@Column(name = "RESPONSE_TRANS_ID", length = 100)
	public String getResponseTransId() {
		return this.responseTransId;
	}

	public void setResponseTransId(String responseTransId) {
		this.responseTransId = responseTransId;
	}

}
