package ops.gateway.entities;
// Generated Feb 1, 2020 10:38:55 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SystemConfiguration generated by hbm2java
 */
@Entity
@Table(name = "system_configuration", catalog = "ops_pay_service", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SYSTEM_PARAM_CODE", "IS_ACTIVE" }))
public class SystemConfiguration implements java.io.Serializable {

	private Byte systemConfigurationId;
	private String systemParamCode;
	private String systemParamName;
	private String systemParamValue;
	private byte isActive;
	private Byte isEncrypted;
	private String createdBy;
	private String updatedBy;
	private Date updatedDate;
	private Date createdDate;

	public SystemConfiguration() {
	}

	public SystemConfiguration(String systemParamCode, byte isActive) {
		this.systemParamCode = systemParamCode;
		this.isActive = isActive;
	}

	public SystemConfiguration(String systemParamCode, String systemParamName, String systemParamValue, byte isActive,
			Byte isEncrypted, String createdBy, String updatedBy, Date updatedDate, Date createdDate) {
		this.systemParamCode = systemParamCode;
		this.systemParamName = systemParamName;
		this.systemParamValue = systemParamValue;
		this.isActive = isActive;
		this.isEncrypted = isEncrypted;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYSTEM_CONFIGURATION_ID", unique = true, nullable = false)
	public Byte getSystemConfigurationId() {
		return this.systemConfigurationId;
	}

	public void setSystemConfigurationId(Byte systemConfigurationId) {
		this.systemConfigurationId = systemConfigurationId;
	}

	@Column(name = "SYSTEM_PARAM_CODE", nullable = false, length = 50)
	public String getSystemParamCode() {
		return this.systemParamCode;
	}

	public void setSystemParamCode(String systemParamCode) {
		this.systemParamCode = systemParamCode;
	}

	@Column(name = "SYSTEM_PARAM_NAME", length = 200)
	public String getSystemParamName() {
		return this.systemParamName;
	}

	public void setSystemParamName(String systemParamName) {
		this.systemParamName = systemParamName;
	}

	@Column(name = "SYSTEM_PARAM_VALUE", length = 100)
	public String getSystemParamValue() {
		return this.systemParamValue;
	}

	public void setSystemParamValue(String systemParamValue) {
		this.systemParamValue = systemParamValue;
	}

	@Column(name = "IS_ACTIVE", nullable = false)
	public byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(byte isActive) {
		this.isActive = isActive;
	}

	@Column(name = "IS_ENCRYPTED")
	public Byte getIsEncrypted() {
		return this.isEncrypted;
	}

	public void setIsEncrypted(Byte isEncrypted) {
		this.isEncrypted = isEncrypted;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UPDATED_BY", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
